homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Amsterdam
  internal_url: !secret url_internal
  #external_url: !secret url_external
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# Home Connect API
home_connect:
  client_id: !secret homeconnect_client_id
  client_secret: !secret homeconnect_client_secret

# Sensors
sensor:
  # DSMR Reader
  - platform: dsmr_reader

binary_sensor:
  - platform: tod
    name: Night
    after: sunset
    before: sunrise

# Weather services
weather:
  - platform: buienradar
    name: Home

# Virtual entities
input_boolean:
  mode_vacation:
    name: Vakantie modus
    icon: mdi:beach

input_number:
  replay_days_back:
    name: Aantal dagen
    icon: mdi:calendar-today
    max: 30
    min: 1

# Dashboards
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module
    - url: /hacsfiles/light-popup-card/light-popup-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-card-preloader/lovelace-card-preloader.js
      type: module
    - url: /hacsfiles/lovelace-hui-element/hui-element.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/restriction-card/restriction-card.js
      type: module
    - url: /hacsfiles/rgb-light-card/card.js
      type: module
    - url: /hacsfiles/rgb-light-card/card.js
      type: module
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /local/font.css
      type: css
  dashboards:
    lovelace-mobile:
      mode: yaml
      title: Mobile
      icon: mdi:cellphone-iphone
      show_in_sidebar: true
      filename: dashboards/mobile.yaml

frontend:
  themes: !include_dir_merge_named themes

# Includes
light: !include lights.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
#panel_custom: !include panel_custom.yaml
homekit: !include homekit.yaml

